# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 07:50
from __future__ import unicode_literals

import Dj666.system.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vft', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('sex', models.IntegerField(choices=[('男', 1), ('女', 0)])),
                ('desc', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='dog',
            name='headimg',
            field=models.ImageField(storage=Dj666.system.storage.ImageStorage(), upload_to='vft'),
        ),
    ]
