# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20171108_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maker',
            name='name',
            field=models.CharField(choices=[('大众', 'vv'), ('丰田', 'toyota')], max_length=20),
        ),
    ]
