# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20171109_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mk', related_query_name='mk', to='polls.Maker'),
        ),
    ]
