# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_stu_stuinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stuinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='stuinfo',
            name='code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='polls.Stu'),
        ),
    ]
