# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='SonCat',
            fields=[
                ('cat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.Cat')),
            ],
            bases=('polls.cat',),
        ),
        migrations.CreateModel(
            name='ProxyCat',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('polls.cat',),
        ),
    ]
